Add Config and Migration, Update Adapter.php
yiisoft/queue-db pull request #11
Opened 2024-03-28 00:20 UTC by aphraoh

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ❌
| Breaks BC?    | ❌

2024-03-31 22:20 UTC, aphraoh commented
@vjik could you please merge this one too. Thanx

2024-04-01 11:43 UTC, xepozz requested changes

2024-04-01 11:43 UTC, xepozz commented on composer.json
> +        "yiisoft/db-migration": "^1.0",
Let's move it to the "suggests" section

2024-04-01 11:43 UTC, xepozz commented on composer.json
> +        "yiisoft/mutex-file": "^1.0",
Use `yiisoft/mutext` instead

2024-04-01 11:43 UTC, xepozz commented on src/Adapter.php
> +        $this->mutex = new FileMutex(__CLASS__ . $this->channel, sys_get_temp_dir());
Use https://github.com/yiisoft/mutex/blob/master/src/MutexFactoryInterface.php#L19 instead

2024-04-01 11:43 UTC, xepozz commented on src/Adapter.php
> +        $new->mutex = new FileMutex(__CLASS__ . $this->channel, sys_get_temp_dir());
Use https://github.com/yiisoft/mutex/blob/master/src/MutexFactoryInterface.php#L19 instead

2024-04-01 11:43 UTC, xepozz commented on src/Adapter.php
> +            }
```suggestion
                continue;
            } 
            if (!$repeat) {
                break;
            } 
            if ($timeout > 0) {
                sleep($timeout);
            }
```

2024-04-01 11:43 UTC, xepozz commented on src/Adapter.php
> +        while (1) {  // TWK TODO while condition should not be hard coded, use LoopInterface
Why wouldn't you use it now?

2024-04-02 11:26 UTC, vjik commented on config/di.php
You can remove configuration with empty array.

2024-04-02 12:27 UTC, aphraoh commented on config/di.php
Hi @vjik, when I do that there is issues either with composer update or something else, I can not remember what it was or why, can we leave it for now?

2024-04-02 12:28 UTC, closed without merging